FROM python:latest as builder
# Run a shell command to extract the current IP address and set it as an environment variable
RUN export CURRENT_IP=$(sh -c "ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'")
# Set the environment variable for the application to use
ENV CURRENT_IP=${CURRENT_IP}
WORKDIR /app
COPY ./backend/requirements.txt /app/
RUN python3 -m pip install --upgrade pip
RUN pip install -q -U -r requirements.txt

FROM builder
WORKDIR /app
COPY --from=builder /app /app/
EXPOSE 8000
ENV FLASK_APP=main.py
ENV FLASK_ENV=production
CMD ["python", "main.py"]